### ISSUE TITLE
Add explanatory diagram to main readme (if combining `state` and `template`)

### ISSUE THREAD

**Issue by karol-depka** [BioPhoton/rx-angular#112]

**Comment by BioPhoton** [comment]
Could you provide a bit more information on what this issue is about?

> if combining `state` and `template`
The libs, if this is the question will not get combined.

Just let me know how we cam proceed :)

**Comment by karol-depka** [comment]
combining - I mean use cases where state and template are used together

**Comment by karol-depka** [comment]
The overarching theme is to put more cool and informative stuff in main readme :).

**Comment by BioPhoton** [comment]
Sounds good

**Comment by BioPhoton** [comment]
I'll close this issue until we know how to proceed.
