### ISSUE TITLE
Create Global State example

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#113]
# Injecton Token:

```typescript
@Injectable({ providedIn: 'root' })
export class MessageService {
  readonly messages$ = this.state.select('messages');

  constructor(private state:RxState<MessageServiceState>()) {
    this.state.set(initState);
  }

  add(message: string) {
    this.state.set('messages', oldState => [...oldState.messages, message]);
  }
}
```
Mention boildr plate best one

# Compistion and manual implementation:

```typescript
@Injectable({ providedIn: 'root' })
export class MessageService implement OnDetroy {
 private readonly state = new RxState<MessageServiceState>();
  readonly messages$ = this.select('messages');

  constructor() {
  
    this.state.set(initState);
  }

  add(message: string) {
    this.set('messages', oldState => [...oldState.messages, message]);
  }

ngOnDetroy () {
this.state$.ngOnDetroy (); 
}

}
```

Mention we don't expose the full API => avoid misusage to avoid

# Extending the global service:

```typescript
@Injectable({ providedIn: 'root' })
export class MessageService extends RxState<MessageServiceState> {
  readonly messages$ = this.select('messages');

  constructor() {
    super();
    this.set(initState);
  }

  add(message: string) {
    this.set('messages', oldState => [...oldState.messages, message]);
  }

  clear() {
    this.set({ messages: [] });
  }
}
```

Mention downsides expose private API

**Comment by Karnaukhov-kh** [comment]
Test

**Comment by BioPhoton** [comment]
related to #111

**Comment by BioPhoton** [comment]
https://github.com/cartant/ts-action
We could use it in our examples

**Comment by tayambamwanza** [comment]
@BioPhoton I'm trying to migrate from @codewithdan/observable-store to @rx-angular/state, it looks pretty similar here, but I managed to only find this issue, where can I find this on offical docs site or is it yet to be updated?

This is the one I find on the docs site: [Using RxState as Global State](https://github.com/rx-angular/rx-angular/blob/master/libs/state/docs/snippets/manage-global-state.md)

**Comment by BioPhoton** [comment]
We decided to skip tsaction example for now.
if you like you can create a demo. Also and especially for Dan's store. 😁👍

**Comment by tayambamwanza** [comment]
@BioPhoton thanks, I managed to succesfully re-implement on my side, it's actually a lot less code thats needed for rx-angular/state anyway, so I'll contribute a demo at some point.
