### ISSUE TITLE
@rx-angular/state - Create transformation helper

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#118]
# DRAFT

The common operations on data structures like Arrays, Objects, Linked lists, etc are very often repetitive lines. The mentioned transformation helpers should automate it.

## Signature

A transformation helper should be directly placed in a reducer function:
`this.connect('list', newItem$, (state, newItem) => addItem(state.list, newItem))`.

The first operator is providing the data structure to interact with, the second is the value.

## Helpers
Following Data structures and transformations should be considered:

- Array
The outcome of the last discussion:
remove/update by comparison function is needed. comparisonFn vs. transformationFn to be decided by @Karnaukhov-kh 

  - `insert('list', items)` or  `insert('list', item)`
  - `remove('list', items)` or  `remove('list', item)` 
  - `update('list', items)` or  `update('list', item)` 
  - `sortBy(keysInOrder)` or `sortBy(keysSortMapInOrder)`
  - `toDictianary('list', prop1)`

- Object
  - `setProp(prop, user)`
  - `deleteProp(prop)`
  - `toggle(obj, 'isOpen')`

Further structures to consider:
- Map
- Set
- LinkedList

## Usage

```typescript
const list$ = this.servce.list$;
state.connect('isOpen', trigger$, (s, o) => toggle(s, 'isOpen')))

const list$ = this.servce.list$;
state.connect('dict1', list$, (s, l) => toDictionary(s.list, l))

const newItem$ = this.service.newItems$;
state.connect('list', id$, (s, i) => delete(s.list, i))
```

**Comment by Phhansen** [comment]
This looks a lot like [ngrx entity adapter collection methods](https://ngrx.io/guide/entity/adapter#adapter-collection-methods)? Albeit they are made for a collection of items.

Maybe look into the naming used in `@ngrx/entity`? it is pretty well defined.

I love the Object helpers here though 💪
