### ISSUE TITLE
@rx-angular/state - @ViewChildren/@ContentChildren [best practice]

### ISSUE THREAD

**Issue by ysoulaim** [BioPhoton/rx-angular#144]
It is documented how to handle `@Inputs` & `@Outputs`, but what would be the cleanest way to handle `@ViewChildren` & `@ContentChildren` and distinct changes?

Would it be a good idea to store them in the local store using a setter method, just like inputs?

Thanks!

**Comment by BioPhoton** [comment]
@hoebbelsB I think this is where you have expertise. :)

**Comment by BioPhoton** [comment]
Closed for now due to #167
