### ISSUE TITLE
Problem: selectSlice always returns a type of Observable<unknown>

### ISSUE THREAD

**Issue by christianacca** [BioPhoton/rx-angular#146]
Take the following example:

```ts
const vm$ = this.state.select(
  distinctUntilSomeChanged(['list', 'isItemRendered']),
  map(({ list, isItemRendered }) => ({
    list, isItemRendered
  }))
);
```

This produces the following return type:

![image](https://user-images.githubusercontent.com/886590/85196074-81919e80-b2cf-11ea-8abd-7a47ce155eb9.png)

Compare this with the equivalent code that uses `selectSlice`:

```ts
const vm$ = this.state.select(
  selectSlice(['list', 'isItemRendered'])
);
```

This produces the following return type:

![image](https://user-images.githubusercontent.com/886590/85196101-b7cf1e00-b2cf-11ea-9171-bfbc3d14eee7.png)

**Comment by hoebbelsB** [comment]
Thx for reporting. We are aware about this issue and are already discussing possible solutions. I guess it will be fixed by the end of the week :)

**Comment by christianacca** [comment]
Excellent and thanks

**Comment by hoebbelsB** [comment]
hi @christianacca, one of our fellow contributors fixed this issue. Look at his pr: https://github.com/BioPhoton/rx-angular/pull/150

**Comment by christianacca** [comment]
Nice thanks guys
