### ISSUE TITLE
"pluck" behavior in RxState#select()

### ISSUE THREAD

**Issue by hoebbelsB** [BioPhoton/rx-angular#149]
The current implementation uses "pluck" internally, which will raise errors if you try to pluck a property of an null/undefined state slice.
For convenience we should introduce a "safePluck" pipe which will always return a valid value instead of an error. It should return null/undefined (dependent on the state slice).

**Comment by Karnaukhov-kh** [comment]
Just a note. Pluck issue fixed in RxJS 6.3: https://github.com/ReactiveX/rxjs/pull/5524.

**Comment by BioPhoton** [comment]
We need to ensure that as after updating to angular 10 we also use rxjs 6.5.5 now

**Comment by hoebbelsB** [comment]
hmmm, this one returns undefined on null or undefined values. To be really consistent with the other APIs we should return `null` on plucking on `null` and `undefined` when plucking something `undefined`. Suggestions?

**Comment by BioPhoton** [comment]
fixed in 1.4.0
