### ISSUE TITLE
@rx-angular/state 1.0.0

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#17]
Restructure state management logic under new package `state`.

**Refactoring**
- [x] Move reusable logic of `rxjs-state` into `@ngx-rx/ts-etc` and `@ngx-rx/rxjs-etc`
- [x] Keep duplicate in `@ngx-rx/rxjs-state` until we move it into another repo.

**Public API**
- [x] RxState
   - [x] $
   - [x] set
   - [x] connect
   - [x] get
   - [x] select
   - [x] hold
- [x] Operators
   - [x] select
   - [x] stateful

**Docs**
- [x] JsDocs
- [x] API
- [x] Readme etc

**Comment by BenjaminDiscoVergy** [comment]
please do also not forget the link in the main readme.md under the "Angular" headline

**Comment by BioPhoton** [comment]
Thx @BenjaminDiscoVergy  did it!
