### ISSUE TITLE
selectSlice still a problem?

### ISSUE THREAD

**Issue by christianacca** [BioPhoton/rx-angular#177]
Upgraded to 1.3 with the hope of being able to use `selectSlice` rather than a combination of `distinctUntilSomeChanged` and `map`, and it doesn't seem to be giving the result I expected.

Here's the existing code I was hoping to be able to refactor:

![image](https://user-images.githubusercontent.com/886590/87255133-16775a00-c480-11ea-8881-8a58c02e3476.png)

Here's the refactored code:

![image](https://user-images.githubusercontent.com/886590/87255161-4aeb1600-c480-11ea-8463-af0138b08e64.png)

The typescript compiler isn't happy with this as can be seen:

![image](https://user-images.githubusercontent.com/886590/87255177-622a0380-c480-11ea-9755-6495c8fb3bed.png)

I thought I should be able to use selectSlice as above. Am I missing something?

**Comment by hoebbelsB** [comment]
thanks for reporting, we will review this asap. sorry for the inconvenience!

**Comment by hoebbelsB** [comment]
@christianacca this seems to be an issue with the tsconfig `CompilerOption` `"strictNullChecks": true`. Can u confirm this behavior? We will investigate on this

**Comment by christianacca** [comment]
strict null checks is on in my project. Here's the complete settings for reference:

```json
{
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2019", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "baseUrl": ".",
```

**Comment by BioPhoton** [comment]
Hi @christianacca 

Try to install 1.3.4 and let me know if it works

**Comment by christianacca** [comment]
Just tried with 1.3.4 and get an error (tried closing VS code after install just in case!).

![image](https://user-images.githubusercontent.com/886590/88585960-af46d180-d04b-11ea-9a00-c7e0edefd137.png)

**Comment by BioPhoton** [comment]
@kajetansw do you have any clue why this is not working?

**Comment by christianacca** [comment]
My typescript chops are not up to par with what I already see in this repo!

I can create a repo with a small scenario that shows the problem if that helps?

**Comment by kajetansw** [comment]
@christianacca Hi, that would be very helpful! I wanted to recreate your use-case as closely as I could, but I don't know how accurate I was (e.g. I don't know which versions of Angular and TypeScript do you use). 
Nevertheless this piece of code seems to be working (see HelloComponent):
https://stackblitz.com/edit/angular-ivy-vaeayv
Am I missing something?

**Comment by christianacca** [comment]
I'm using latest angular 10.0.5 with Typescript 3.9.6.

I'll get a git repo that demonstrates the problem in case stackblitz isn't quite able to reproduce the typescript compilation that is happening.

I'll add a link here to the github repo when it's ready (hopefully by eod tomorrow)

**Comment by BioPhoton** [comment]
Hi @christianacca 
> I can create a repo with a small scenario that shows the problem if that helps?

Any news here?

**Comment by christianacca** [comment]
Sorry guys I haven't got the repo for you yet. I started but it seems that
it's something very specific to the use of generics that I'm using to
define the interface for state. I will have time this weekend to get this,
so stay tuned :-)

**Comment by christianacca** [comment]
Here's the repo: https://github.com/christianacca/rx-state-playground

See these lines of code that demonstrate the problem: https://github.com/christianacca/rx-state-playground/blob/0a731f5d0e023963deffe191fefe162f314effcb/apps/main/src/app/app.component.ts#L20-L25
