### ISSUE TITLE
[unpatch] Issue with routing.

### ISSUE THREAD

**Issue by Karnaukhov-kh** [BioPhoton/rx-angular#183]
If we use `[unpatch]` on links/buttons that trigger navigation it results in weird behavior. 
View either stuck completely or until you trigger change detection in some other way.

After click console shows a warning
![image](https://user-images.githubusercontent.com/15088626/87874027-11aa2d00-c9cf-11ea-8502-4fd4481db5c8.png)

Example made in the branch [unpatch_and_routing_reproduce](https://github.com/BioPhoton/rx-angular/tree/unpatch_and_routing_reproduce) (run template demo)

**Comment by BioPhoton** [comment]
I would suggest just not running the unpatching when we are in a routre link

**Comment by hoebbelsB** [comment]
Yes, we can't really do anything about it. The warning will fade eventually if you turn off NgZone completely ;). Maybe this issue will be fixed by the angular team with the next major releases. But for now I agree with @BioPhoton: don't use `unpatch` on `routerLink` buttons.

**Comment by Karnaukhov-kh** [comment]
Looks like we can just update docs a bit and we're good to go?

**Comment by hoebbelsB** [comment]
that sounds reasonable :)
