### ISSUE TITLE
get('mykey') should return the value of `mykey`

### ISSUE THREAD

**Issue by christianacca** [BioPhoton/rx-angular#193]
I was expecting `get` that takes a key to return the value of that key.

So I would expect to be able to do this:

```ts

class MyComponent extends RxState<{ entity: Application }> {
  get application(): Application {
    return this.get('entity');
  }
}
```

But in fact it fails:

![image](https://user-images.githubusercontent.com/886590/88597354-f9857e00-d05e-11ea-8191-7901b517bb09.png)
![image](https://user-images.githubusercontent.com/886590/88597378-073b0380-d05f-11ea-9198-cdb81f43d98f.png)

Shouldn't the signature of `get` be changed from this:

```ts
get<K1 extends keyof T>(k1?: K1): T | Partial<T>;
```

To this:

```ts
get<K1 extends keyof T>(k1: K1): T[K1];
```

**Comment by Karnaukhov-kh** [comment]
Hi @christianacca. Thank you for reporting. We will check and ping you back as soon as possible.

**Comment by BioPhoton** [comment]
Cc @JakubDospial
