### ISSUE TITLE
bug(template/let): cannot use function with returning observable

### ISSUE THREAD

**Issue by muuvmuuv** [BioPhoton/rx-angular#220]
# Description

I would like to use a function in `rxLet` which returns the Observable. Unfortunately it runs into an infinite loop.

# Steps to Reproduce the Issue

Repo: https://github.com/muuvmuuv/rx-angular-issue-220

# Environment

```
Angular CLI: 10.0.5
Node: 12.18.0
OS: darwin x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cli                      10.0.5
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by hoebbelsB** [comment]
hi @muuvmuuv! thx for reporting an issue :).

Though this should not end up in an endless loop, this is definitely not a recommended approach, especially when not using `ChangeDetectionStrategy.OnPush`.
Template functions are getting executed/re-evluated on ANY ChangeDetection cycle which can lead to very serious performance issues. (see https://medium.com/showpad-engineering/why-you-should-never-use-function-calls-in-angular-template-expressions-e1a50f9c0496)
The `*rxLet` directive will schedule a new ChangeDetection cycle, whenever it gets a "new" Observable. If this cycle leads to a new Observable connected to the `*rxLet` directive, this will ultimately end in an endless loop. We will investigate how we can at least minimize the negative effects.

You could have a look at our [transformation helpers](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/api/overview.md#transformation-helpers), especially the `toDictionary` function could help you in this scenario. Try to have an observable _property_ from which you can read inside the template.

I hope I could help you. If you have any further questions, feel free to ask :)!

**Comment by muuvmuuv** [comment]
Oh my... I totally forgot about this, thank you!

Do you mind have a look at it again? I have updated it a little and moved that zone into its own component: https://github.com/muuvmuuv/rx-angular-issue-220/blob/master/src/app/state/zone/zone.component.ts#L20-L26

**Comment by hoebbelsB** [comment]
I have not looked into details, but looks better. Does it work? Btw. you should use a [`trackByFn`](https://medium.com/@jinalshah999/trackby-with-ngfor-directives-in-angular-application-bd4d0db288eb) in your `*ngFor` just to make sure your list is not re-rendering when not needed :).

Another thing you think about is having your `zone-component` be a presentational-only component. It does not need to know anything about the state service itself. You could just provide it with all the observables it needs via `@Input()`. But thats a design decision everyone has to make on his/her own.

Have a look [here](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/snippets/passing-observables-directly.md) or if you want to have some more detailed information [here](https://indepth.dev/presentational-components-with-angular/). @LayZeeDK  ;)

**Comment by muuvmuuv** [comment]
Ohh, I was not aware about `trackBy`. This is great!

The thing with `zone-component` is that it is nested (inherits itself) based on an item's nested level. I am still struggling how I should implement the loop. Anyway thank you, maybe I can use the presentational-strategy somewhere else!
