### ISSUE TITLE
State: Select Observables do not emit for "undefined"

### ISSUE THREAD

**Issue by mfusser** [BioPhoton/rx-angular#261]
# Description

When using select in rx-angular/state the resulting observable does not emit for `undefined`.

# Steps to Reproduce the Issue

Select any field and subscribe to the resulting Observable.
Set the value of the field to undefined.

[stackblitz](https://stackblitz.com/edit/angular-ivy-fxdzbm?devtoolsheight=33&file=src/app/app.component.ts)

# Environment
Angular: 10.0.11
Rx-Angular/State: 1.3.4
Rxjs: 6.6.2
Tried in Chrome 83.0.4103.61

Please let me know if you need any further information.

**Comment by hoebbelsB** [comment]
hi @mfusser this is not really an issue. It is intended behavior. The select method and all other operators provided by this library will never emit undefined values.

* [stateful](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/api/operators/stateful.md)
* [selectSlice](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/api/operators/select-slice.md)
* [distinctUntilSomeChanged](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/api/operators/distinct-until-some-changed.md)

But as I was looking for other sources to show you how well this behavior is documented, I've come to the conclusion that we have to state this at a more prominent place.

I hope I could help you :+1:

**Comment by mfusser** [comment]
Thanks for your quick answer.
I know I already closed the issue, but i have a follow up question:
Should `get()` then not always return a `Partial<T>` and `.$` return a `Observable<Partial<T>>`?
Otherwise you might unexpectedly get `undefined` when a field was not initialized yet, even though the types do not allow it.

[Stackblitz for an example](https://stackblitz.com/edit/angular-ivy-d2sncc?devtoolsheight=33&file=src/app/app.component.ts)
