### ISSUE TITLE
selectSlice: wait until all properties are defined before emitting

### ISSUE THREAD

**Issue by ysoulaim** [BioPhoton/rx-angular#281]
Currently, when using `selectSlice`, the resulting observable **emits whenever every property of the selected slice changes**. Is there a way to only emit if all the properties of the selected slice change `just like combineLatest` ? 

A solution would be to select each piece and use `combineLatest`, but that would create a lot of boilerplate. It would be nice to be able to pass an argument to `selectSlice` to wait for all properties to be defined before emitting.

**Comment by hoebbelsB** [comment]
hi @ysoulaim thanks for reporting!! :+1: 
I recently had a discussion with @BioPhoton about this exact issue. We are aware of this behavior and are concerning solutions for this. If I understood correctly, the problem you are facing is that the `selectSlice` operator emits it's first change even if not every selected property has a value until then, is this the issue?

**Comment by ysoulaim** [comment]
Hi @hoebbelsB ! 
It is exactly this same exact issue. Glad to know you are working on it :) 
I managed to use `combineLatest` with `select`, but the resulting code was not clean.

**Comment by hoebbelsB** [comment]
> Hi @hoebbelsB !
> It is exactly this same exact issue. Glad to know you are working on it :)
> I managed to use `combineLatest` with `select`, but the resulting code was not clean.

ok, we will keep you updated on the progress :+1:

**Comment by Karnaukhov-kh** [comment]
Hi @ysoulaim. This issue is now fixed and released. Thank you for reporting 👍

**Comment by ysoulaim** [comment]
@Karnaukhov-kh that is awesooome ! Thank you for keeping me informed :)
