### ISSUE TITLE
let directive: pass error value as context to error template when using template anchors

### ISSUE THREAD

**Issue by codingnuclei** [BioPhoton/rx-angular#285]
# Problem Solved By The Feature

Currently if using template anchors the error template will receive a context $error = true.
With no context of the actual error

https://github.com/BioPhoton/rx-angular/blob/e1fe3b381d85aaf232873a6655bed08b533692d1/libs/template/src/lib/let/let.directive.ts#L334

# Solution

Pass the error as the implicit context for the view:

`this.templateManager.updateViewContext({
       $implicit: error,
       $error: true,
  });`

**Comment by BioPhoton** [comment]
Hi @codingnuclei!
Thanks for your feedback!

The first implementation had the error as value instead of treu for $error. 

What would you do with the original error?
Just try to gather more information...

**Comment by codingnuclei** [comment]
For me the observable is a network request. So the errors are network errors. 

It would be nice to display different errors messages based on the error... Not just "There has been an error".

Out of interest why was it changed from the original?

**Comment by BioPhoton** [comment]
Hi @codingnuclei.

Can you take a look at the PR #295.

There i implemented your request is a slightly different way. Let me know what you think.

**Comment by codingnuclei** [comment]
Yea that solves the issue nicely.

I like the futures of being able to access the last value too in the future. Although not required for my use case, I can definitely see other use cases that would need it!
