### ISSUE TITLE
Error: Class constructor RxState cannot be invoked without 'new' in stackblitz

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#3]
For some reason it doesn't work on stackblitz.

https://stackblitz.com/edit/ngx-rx-state-demo?file=package.json

**Comment by Bretto** [comment]
Thank you :) https://slides.com/bretto/f/fullscreen

**Comment by andreElrico** [comment]
Any updates?

same error for ng-run.com;

Filed an issue https://github.com/alexzuza/ng-run-issue-tracker/issues/11

**Comment by BioPhoton** [comment]
IMHO something related to compilation. Unfortunately I had no success last time and no time to work on that issue.

 I could try to compile rxjs-state into ngx-rx-state as we need it anyway?

**Comment by andreElrico** [comment]
You mean you extends ngx-rx-RxState from a JS-class that is somewhere in dist/rx-state? Have you filed this on stackblitz ?

**Comment by BioPhoton** [comment]
> Have you filed this on stackblitz

Not yet as I'm not sure if it is related to them or to us.

**Comment by BioPhoton** [comment]
https://github.com/vmware/clarity/issues/4094
Probably the target version.

I'll have a look after the tooling is ready

**Comment by yjaaidi** [comment]
Hey buddy and everyone else!

I stumbled upon the same issue with my app's unit-tests using Jest.

In fact, it is compilation issue. We fell in an edge case here.
The common thing with stackblitz and jest is that they are using `ngx-rx-state`'s `UMD` files which are transpiled to ES5... but `RxState` extends `RxjsState`  (from `rxjs-state`) which is simply transpiled to ES2015 so `_super.call(this)` fails.

I can only see three solutions:
**A. Transpile `rxjs-state` to es5.
B. Use ng-packagr for `rxjs-state`.
C. Never use `ngx-rx-state` on Stackblitz and never test your code when using it 😜**

**Solution A**  might not be the best choice as it would force everyone to use the ES5 library.
**Solution B**  can be surprising but seems the best to me as it will provide ES5 umd for everyone and es2015 files for Angular 
**Solution C** is the currently applied solution

[Alan](https://github.com/alan-agius4) is probably the person who could help us make the best choice.

@BioPhoton let me know what you think and I can shoot a PR.

**Comment by LayZeeDK** [comment]
I use ng-packagr for my RxJS microlibraries. It's useful for a lot more targets than Angular. Basically covering your behind for every situation.

**Comment by yjaaidi** [comment]
Perfetto!
I'll take care of the PR.

**Comment by BioPhoton** [comment]
Amazing thanks for all the feedback and help!

**Comment by BioPhoton** [comment]
Solved: 
https://stackblitz.com/edit/rx-angular-state-demo?file=src%2Fapp%2Fcounter.component.ts
