### ISSUE TITLE
[Question/ Discussion] Querying nested property with select()

### ISSUE THREAD

**Issue by andreElrico** [BioPhoton/rx-angular#4]
Assumption:
`state.setState({loo: { boo: 42}});`

+ lets select a nested property.

### Current:

`const boo$ = state.select('loo', 'boo');`

### Suggestion: (not sure if there is a REAL advantage)

going `this.formGroup.get()` style:

https://github.com/angular/angular/blob/9e78f55c3275299d5b3da35d8d08875332a7180a/packages/forms/src/model.ts#L742

So the above would become:

`const boo$ = state.select('loo.boo');`

-OR-

`const boo$ = state.select(['loo', 'boo']);`

an advantage I see is that the argument is predictively "one variable", as well as there is a rock solid  and proven angular implementation.

**Comment by BioPhoton** [comment]
Souds good!

The reason the select is here it applies `distinctUntilChanged`, `filter`s out undefined, and `shareReplay`s the selection for multiple subscribers.

The idea why I went with that was it is aligned with `pluck`

**Comment by andreElrico** [comment]
I think its nice to have "syntactic sugar" here. I would keep the "string-cases".

Would it make sense to opt out of `distinctUntilChanged()` so the consumer can write its own version. If so I would design the API like this.

+ const boo$ = state.select(['loo', 'boo']); // nest case ... is it possible to "double spread for pluck?

+ const boo$ = state.select(['loo']);  // normal case

+ const boo$ = state.select(map(s => this.lol ? s?.foo : s?.foo?.bar )); // with fun

eg:

+ const boo$ = state.select(['loo'], {noDistinct: true});  << plus other options to come in the future

In your select function you can then simply test your case with

(firstArgument = your selecter )

if (`firstArgument[0]`) will be `undefined` for function and "true" for all strings except `""` (empty)

**Comment by andreElrico** [comment]
Something along those lines : https://stackblitz.com/edit/typescript-es2gu6?file=index.ts

**Comment by BioPhoton** [comment]
Hi @andreElrico 
Would in a first step #5 help?

**Comment by hoebbelsB** [comment]
@andreElrico the problem I see is that the rxjs-state in its core is not targeted to fit to any specific framework. It only comes with a peer dependency on rxjs, but not angular. The current implementation mirros the behavior of the [pluck operator](https://rxjs-dev.firebaseapp.com/api/operators/pluck) which is the correct approach imho.

**Comment by BioPhoton** [comment]
My 2 cent:
The package has a hard dependency to angular.
The explanation that it mirrors pluck is valid and I agree. I would not implement that dot notation ATM.

Please feel free to reopen the issue at any time.
