### ISSUE TITLE
@rx-angular/state - Expose select method as standalone operator

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#6]
Providing the `select` method as a standalone operator would enable the user to compose state from other services like ngrx/store reactively.

- [ ] Implement standalone operator
- [ ] Try to reduce typing
- [ ] Tests
- [ ] Docs
- [ ] Examples

**Comment by hoebbelsB** [comment]
other than a collision with the [select](https://ngrx.io/api/store/select) function from ngrx/store I see no issues with that. But maybe you provide the operator under a different name?
