### ISSUE TITLE
@rx-angular/state reactive @Output binding needs improvement in usage 

### ISSUE THREAD

**Issue by hoebbelsB** [BioPhoton/rx-angular#60]
kind of refers to: #57 and #27. as discussed [here](https://github.com/BioPhoton/rx-angular/pull/57/files#r416960128) we need a seperate solution for handling `@Output()` bindings. The `select()` operator/method returns a shared and replayed observable which is not how angular typically handles Output bindings (`EventEmitter<T>` aka `Subject<T>`). Thus we have to come up with a solution for this.

We could combine the `$` property with a custom operator which has the same API as `select` but returns a cold observable. 
Another way to handle Output bindings would be to use `hold` and trigger a subject based on a selection. Exactly how stated in #27 .

**Comment by BioPhoton** [comment]
I'm not sure if outputs need all of selects internal behavior.
Imho distinctUntilChanged should be enough.

I assume a common use case is:
- pluck one or many properties
- transform one or many plucked properties

Imho the planned distinctUntilKeysChanged operator could solve this?

**Comment by hoebbelsB** [comment]
> I'm not sure if outputs need all of selects internal behavior.
> Imho distinctUntilChanged should be enough.
> 

thats exactly what i meant by stating "same API as `select` but cold".

> I assume a common use case is:
> 
> * pluck one or many properties
> * transform one or many plucked properties
> 
> Imho the planned distinctUntilKeysChanged operator could solve this?

yes, those are the use cases. distinctUntilKeysChanged could help!

**Comment by BioPhoton** [comment]
Do we have an issue for the operator?
Would add it to the feature first minor bump if possible..

**Comment by hoebbelsB** [comment]
Shouldn't this be part of #53 aswell? i see Output bindings are ticked, which is... wrong? :p

**Comment by BioPhoton** [comment]
Well... 😅 In my head they are solved. It's manually usind 2 operators.

The resulting operator is a convenience method for the user.

We can u tick if it is confusing.

**Comment by BioPhoton** [comment]
Could we setup a minimal uscase in a stackblitz or our experiments app for this?

**Comment by Karnaukhov-kh** [comment]
Hi. Not sure it deserves a separate issue, so I'll write here :). What about use case like this:

- List component which renders item components (values are some objects) through `*ngFor="let item of items$ | async"`.
- Item has `@Output change =  this.select()` (or `this.select('some_primitive')`) doesn't matter.
- Item `@Input` is setter which accepts item object and doing `this.set({...item});`
- Default item state was undefined(?) and then becomes an object. That means after `set()` from setter Output will trigger. If new item was added to the list it also emmidiately triggers change output.

But some side effects might be binded to this item change output and user definitely don't want to trigger it after item just got rendered. So basically user needs to declare Item Output like this `change = this.select().pipe(skip(1));` to avoid first emission. In this case standard behavior of select() method is not fitting so user probably will use default EventEmitter.

A bit messy stackBlitz demo: https://stackblitz.com/edit/rx-angular-state-test?file=src%2Flist%2Flist.component.ts

P.S. Maybe separate "expose/reveal" method for Output bindings? :)

**Comment by hoebbelsB** [comment]
hi @Karnaukhov-kh yes, I have experienced the exact same issue by myself in one of my projects. We certainly need some solution specific for output bindings since they have to be cold. Ty for the input :)
