### ISSUE TITLE
@rx-angular/template. Potential issue with globalThis in IE 11.

### ISSUE THREAD

**Issue by Karnaukhov-kh** [BioPhoton/rx-angular#66]
_Disclaimer: haven't tried it yet but tried @ngrx/component_

Hi. I don't know if support for IE 11 is planned but now at least PushPipe not working.

app.module configuration: `@NgModule({ declarations: [ PushPipe, LetDirective, ...], ...})`

Template: `<h1 class="view-controls__heading">{{ title$ | ngrxPush }}</h1>`

Console error
_"globalThis" не определено = "globalThis" is not defined._

![image](https://user-images.githubusercontent.com/15088626/80539274-df7cc680-89af-11ea-9375-11450be019b4.png)

**Comment by BioPhoton** [comment]
Hi @Karnaukhov-kh.

Thanks a lot, for this input!

could you try if one of those polyfills work for you?

- https://github.com/medikoo/es5-ext/blob/master/global.js
- https://github.com/ungap/global-this

If yes let me know so I can do further considerations.

**Comment by Karnaukhov-kh** [comment]
Hi. Both works.
