### ISSUE TITLE
@rx-angular/state -     Ensure `detectChanges` behaves identical to `ɵdetectChanges`

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#68]

**Comment by hoebbelsB** [comment]
by looking at the source of angular I am pretty confident in saying that their are doing the same thing.

[ɵdetectChanges](https://github.com/angular/angular/blob/12fcc7cafe8bf6dd33416847327891b581281774/packages/core/src/render3/instructions/change_detection.ts#L22)

```Typescript
export function detectChanges(component: {}): void {
  const view = getComponentViewByInstance(component);
  detectChangesInternal(view[TVIEW], view, component);
}
```

[detectChanges](https://github.com/angular/angular/blob/12fcc7cafe8bf6dd33416847327891b581281774/packages/core/src/render3/view_ref.ts#L275)
```Typescript
detectChanges(): void {
    detectChangesInternal(this._lView[TVIEW], this._lView, this.context);
}
```
