### ISSUE TITLE
@rx-angular/state. Possible bugs in set() and connect() methods.

### ISSUE THREAD

**Issue by Karnaukhov-kh** [BioPhoton/rx-angular#71]
Hi. Found some possible bugs in set() and connect() methods. Or at least it feels like bugs.

StackBlitz: https://stackblitz.com/edit/rx-angular-state-test?file=src%2Fapp%2Fapp.component.ts

### Setup
app.component
```
export class AppComponent extends RxState<State>  {
  titleString$: Observable<string> = of('RxState tests');
  titleObj$: Observable<Partial<State>> = of({title: 'RxState tests'});

  constructor() {
    super();
  }
}
```
State interface
```
interface State {
  title: string;
  id: number;
}
```
### Connect

**Test 1. Work with properties declared in State interface**

_all "**expected**" conclusions comes from user perspective_

Case 1

`this.connect(this.titleString$, (state, titleString) => ({title: state.title + titleString}));` 

**result:** valid
**expected**: valid
**concern**: titleString is any (but should be string), State can be corrupted

Case 2 

`this.connect(this.titleString$, (state, titleString) => ({...state, id: titleString}))`

**result:** valid
**expected**: not valid, id is a number
**concern**: titleString is any

Case 3

`this.connect(this.titleObj$, (state, titleData) => ({...state, ...titleData}));`

**result:** valid
**expected**: valid
**concern**: titleData is any (but should be `Partial<State>`). State can get props not from interface.

Case 4

`this.connect('id', this.titleString$, (state, titleString) => state.id + titleString)` 

**result:** valid
**expected**: not valid, id is number
**concern**: titleString is any.

**Test 2. Work with properties not declared in State interface**

Case 1

`this.connect(this.titleString$, (state, titleString) => ({...state, randomProp: titleString}));`
**result**: valid
**expected**: not valid, randomProp does not exist in State interface,
**concern**: titleString is any

Case 2

` this.connect('randomProp', this.titleString$);`

**result**: not valid,
**expected**: not valid

Case 3

`this.connect('randomProp', this.titleString$, (state, titleString) => titleString);`

**result**: not valid,
**expected**: not valid
**concern**: titleString is any

### Set

_all "**expected**" conclusions comes from user perspective_

Case 1 (example from docs) 

`this.set('id', 5);` 

**result**: not valid, throws "Argument of type '5' is not assignable to parameter of type 'ProjectValueFn<State, "id">'"
**expected**: valid

Case 2 

`this.set('id', (state) => state.id + ' ')`

**result**: not valid, string is not assignable to number,
**expected**: not valid

**Comment by BioPhoton** [comment]
Thanks for the very detailed explanation!
Will get back with feedback!

**Comment by hoebbelsB** [comment]
hey @Karnaukhov-kh, we have fixed the typing issues in the connect method. See https://github.com/BioPhoton/rx-angular/pull/73. You will find the fixes in the next patch-level release coming soon.

> Set
all "expected" conclusions comes from user perspective
Case 1 (example from docs)
this.set('id', 5);
result: not valid, throws "Argument of type '5' is not assignable to parameter of type 'ProjectValueFn<State, "id">'"
expected: valid

regarding this, the specified overload is not implemented and not planned to be implemented soon. We have updated the docs accordingly. 

Thanks again for your feedback. Feel free to re-open this issue if you have any further questions.

**Comment by Karnaukhov-kh** [comment]
Hi. Awesome, thank you. :)

**Comment by hoebbelsB** [comment]
@Karnaukhov-kh it's awesome you are that much interested in this library. We are currently working on the docs. Would you mind to give us any feedback on this? :)

**Comment by Karnaukhov-kh** [comment]
@hoebbelsB sure. Will get back with another issue soon :).
