### ISSUE TITLE
rx-angular/state - 1.1.0

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#80]
- Standalone operators
  - [x] stateful
  - [x] select #6 
  - [x] distinctUntilSomeChanged [#81]
- Docs
  - [x] Snippets  #61
  - [x] Basics Demo updates
  - [x] #75 

- Other
  - [x] #68 
  - [x] #60 Output bindings (publish vs. publishReplay internal `$`)
  - [x] Rx Tour of heros #87

**Comment by hoebbelsB** [comment]
created a PR for the distinctUntilSomeChanged operator and linked it in your description :)

**Comment by hoebbelsB** [comment]
tour of heroes is ready 2 merge if those other issues are fixed :) #87
