### ISSUE TITLE
Allow custom "stateAccumulator" function for "createAccumulationObservable"

### ISSUE THREAD

**Issue by derbenoo** [BioPhoton/rx-angular#97]
First of all, awesome work! :raised_hands: 

Would it be possible to pass a custom `stateAccumulator` function to the `createAccumulationObservable` function e.g., via the `RxState` constructor? 

The default `stateAccumulator` function only does a [shallow merge](https://github.com/BioPhoton/rx-angular/blob/6d5eb61bbd1cae2652e8ab7c9f278c362fa270a3/libs/state/src/lib/core/accumulation-observable.ts#L23) of the two state objects, I would however need a deep merge of the two states! (e.g., with the `object-assign-deep` package) 

A custom `stateAccumulator` function can already be passed to the `createAccumulationObservable` function, however this function is [called with no parameters](https://github.com/BioPhoton/rx-angular/blob/67298197fecf07a0108bf37eb42fe0f2bc6712af/libs/state/src/lib/rx-state.service.ts#L57) inside the `RxState` class, so I cannot provide it from outside. What would be the best way of making this configurable?

Thanks & Greetings from Munich,
derbenoo

**Comment by BioPhoton** [comment]
Working on it!

**Comment by BioPhoton** [comment]
@derbenoo would you be interested in small description on how to use custom accumulation functions?

Let's say I provide a `.init()` on `RxState`. 

I would need a small file similar to the others in snippets that explains the need and the benefits to the user. 
Let me know if you are interested in this contribution and I can give further info.

Otherwise, expect the feature in the next minor version. :)

**Comment by derbenoo** [comment]
> @derbenoo would you be interested in small description on how to use custom accumulation functions?
> 
> Let's say I provide a `.init()` on `RxState`.
> 
> I would need a small file similar to the others in snippets that explains the need and the benefits to the user.
> Let me know if you are interested in this contribution and I can give further info.
> 
> Otherwise, expect the feature in the next minor version. :)

@BioPhoton thanks for considering my issue! I have rolled out rx-angular/state for our entire UI Component library and have not had a single issue yet! :raised_hands: 

I would gladly contribute to the documentation of the custom accumulation functions, happy to receive further instructions from you! :pray:

**Comment by BioPhoton** [comment]
We can start to work on a list of examples what can be done and it's benefits.
And if there is a implementation draft we can start to document it.

**Comment by BioPhoton** [comment]
@derbenoo the PR is created and a first draft of the implementation is present.
let me know how we can proceed
