### ISSUE TITLE
@rx-angular/state. DistinctUntilSomeChanged feedback/questions.

### ISSUE THREAD

**Issue by Karnaukhov-kh** [BioPhoton/rx-angular#98]
Hi. Here are some thoughts about `distinctUntilSomeChanged`. 👀 

### [Example 1.](https://github.com/BioPhoton/rx-angular/blob/master/libs/state/docs/api/operators/distinct-until-some-changed.md#distinctuntilsomechanged) 
```
distinctUntilSomeChanged<T extends object, K extends keyof T>(
  keyCompareMap: KeyCompareMap<T>
): MonoTypeOperatorFunction<T>;
```
Example:
```
interface Person {
   age: number;
   name: string;
}
// compare the first letters of the name property
const customComparison: KeyValueMap<Person> = {
  name: (oldName, newName) => oldName.substring(0, 3) === newName.substring(0, 3)
};

of(
  { age: 4, name: 'Foo1'},
  { age: 7, name: 'Bar'},
  { age: 5, name: 'Foo2'},
  { age: 6, name: 'Foo3'},
).pipe(
  distinctUntilSomeChanged(customComparison),
)
.subscribe(x => console.log(x));
```
**`KeyValueMap` vs `KeyCompareMap`**

In this example `KeyValueMap` provided. But there is no such type. So should be `KeyCompareMap<Partial<Person>>`? Otherwise it requires a comparison for `age`.

**Passing `KeyCompareMap` directly to `distinctUntilSomeChanged`**

- [x] Signature expects `KeyCompareMap<T>`.

So taking this
```
const customComparison: KeyCompareMap<Partial<Person>> = {
  name: (oldName, newName) => oldName.substring(0, 3) === newName.substring(0, 3)
};
```
and passing inside like this wouldn't work.
```
distinctUntilSomeChanged({
  name: (oldName, newName) => oldName.substring(0, 3) === newName.substring(0, 3)
})
```
> Property 'age' is missing in type '{ name: (oldName: string, newName: string) => boolean; }' but required in type 'KeyCompareMap<{ age: number; name: string; }>'.

**Workaround 1**
```
distinctUntilSomeChanged<{name: string}, "name">({
          name: (oldName, newName) =>
            oldName.substring(0, 3) === newName.substring(0, 3)
        })
```
**Workaround 2**
```
distinctUntilSomeChanged({
          name: (oldName, newName) =>
            oldName.substring(0, 3) === newName.substring(0, 3)
        } as KeyCompareMap<Partial<Person>>)
```
**Workaround 3**
```
 distinctUntilSomeChanged(
          ["name"],
          (oldName, newName) =>
            oldName.substring(0, 3) === newName.substring(0, 3)
        )
```

**Adding default comparison for age.**
```
 distinctUntilSomeChanged({
          name: (oldName, newName) =>
            oldName.substring(0, 3) === newName.substring(0, 3),
            age: undefined
        }),
```
This will result in `oldName`, `newName` as unknown

- [x]   > Property 'substring' does not exist on type 'unknown'.

**Adding custom comparison for age.**
```
 distinctUntilSomeChanged({
          name: (oldName, newName) =>
            oldName.substring(0, 3) === newName.substring(0, 3),
            age: (oldAge, newAge) => oldAge === newAge
        }),
```
Works fine. But user need to provide custom `CompareFn` for all keys.

### Question
Can it be used if `this.select()` returns an array?
```
interface List {
  items: Item[];
  name: string;
  isOpen: boolean;
}

this.select(map(state => state.items), distinctUntilSomeChanged(???????))
```
Right now if we try to write custom `KeyCompareMap` we will kinda work with `Function` type.

Probably `distinctUntilChanged` + custom compare should be used for arrays instead?
```
this.select(
    map(state => state.items), 
    distinctUntilChanged(
        (oldItems, newItems) => oldItems.filter(i => i.asnwered).length === newItems.filter(i => i.answered).length
)
```

**Comment by hoebbelsB** [comment]
Hi @Karnaukhov-kh, sorry for the delayed response!!
Yes, you are right, the example should state `Partial<Person>`.

> Signature expects KeyCompareMap<T>

We have to change it to `KeyCompareMap<Partial<T>>`.

> Property 'substring' does not exist on type 'unknown'

Thanks for pointing out this bug. Working on it.
